### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by ericwern** [gribouille/elm-table-tailwind#3]
I see that infinite scroll/progressive loading is still as a TODO. Do you have any plan for when this is going to be implemented? And also are you planning on having the scroll in the tbody or outside of the tbody?

**Comment by ericwern** [comment]
I'll add some more comments in the same issue that iv'e been thinking about

- Support for subheaders with use of colspan, rowspan
- Add some kind of primary action for clickable row, or a set of possible actions through table config

**Comment by gribouille** [comment]
Hello eric,
I have added the routing of internal actions in elm-table today here:
https://github.com/gribouille/elm-table/pull/7

I will backport these changes in elm-table-tailwind soon and I'll add the infinite scroll.

For clickable row, you can create a custom view, it will be easier than filter the internal actions to check if a row has been clicked.

I would look for subheaders.

**Comment by ericwern** [comment]
@gribouille Great :) Have you given a thought about infinite scroll as well?
